In [135]:
import pandas as pd 
from sklearn.svm import SVC 
#for read our data file having extension of .csv
main_file = pd.read_csv('./data.csv')
main_file

Test No.  point1  point2  point3  ...  point6  point7  point8  Status
0          1   0.200   0.200   0.200  ...   0.200   0.200   0.202       0
1          2   0.199   0.198   0.192  ...   0.200   0.201   0.193       0
2          3   0.200   0.198   0.193  ...   0.181   0.184   0.182       1
3          4   0.200   0.192   0.193  ...   0.183   0.183   0.185       1
4          5   0.197   0.197   0.200  ...   0.173   0.174   0.172       2
5          6   0.201   0.200   0.195  ...   0.174   0.172   0.176       2
6          7   0.200   0.198   0.192  ...   0.165   0.162   0.163       3
7          8   0.193   0.202   0.198  ...   0.202   0.163   0.167       3
8          9   0.202   0.193   0.194  ...   0.159   0.155   0.158       4
9         10   0.200   0.202   0.153  ...   0.158   0.157   0.155       4
10        11   0.201   0.202   0.200  ...   0.132   0.131   0.132       5
11        12   0.198   0.192   0.196  ...   0.132   0.132   0.136       5

[12 rows x 10 columns]

In [136]:
#Separate columns that can be used for features extraction 
input_file = main_file.drop(['Status','Test No.'],axis='columns')
input_file

point1  point2  point3  point4  point5  point6  point7  point8
0    0.200   0.200   0.200   0.202   0.203   0.200   0.200   0.202
1    0.199   0.198   0.192   0.202   0.197   0.200   0.201   0.193
2    0.200   0.198   0.193   0.183   0.183   0.181   0.184   0.182
3    0.200   0.192   0.193   0.202   0.182   0.183   0.183   0.185
4    0.197   0.197   0.200   0.192   0.193   0.173   0.174   0.172
5    0.201   0.200   0.195   0.196   0.173   0.174   0.172   0.176
6    0.200   0.198   0.192   0.162   0.165   0.165   0.162   0.163
7    0.193   0.202   0.198   0.196   0.197   0.202   0.163   0.167
8    0.202   0.193   0.194   0.199   0.152   0.159   0.155   0.158
9    0.200   0.202   0.153   0.154   0.157   0.158   0.157   0.155
10   0.201   0.202   0.200   0.196   0.137   0.132   0.131   0.132
11   0.198   0.192   0.196   0.193   0.192   0.132   0.132   0.136

In [137]:
#Features extraction
input_file['Peak'] = [max(col['point1'],col['point2'],col['point3'],col['point4'],col['point5'],col['point6'],col['point7'],col['point8']) for index, col in input_file.iterrows()]
input_file['Mean'] = (input_file.point1 + input_file.point2 + input_file.point3 + input_file.point4 + input_file.point5 + input_file.point6 + input_file.point7 + input_file.point8)/8
input_file['Mean_Square'] = ( input_file.point1**2 + input_file.point2**2 + input_file.point3**2 + input_file.point4**2 + input_file.point5**2 + input_file.point6**2 + input_file.point7**2 + input_file.point8**2 )/8
input_file['Root_Mean_Square'] = input_file['Mean_Square']**0.5
input_file['Variance'] = ( (input_file.point1 - input_file.Mean)**2 + (input_file.point2 - input_file.Mean)**2 + (input_file.point3 - input_file.Mean)**2 + (input_file.point4 - input_file.Mean)**2 + (input_file.point5 - input_file.Mean)**2 + (input_file.point6 - input_file.Mean)**2 + (input_file.point7 - input_file.Mean)**2 + (input_file.point8 - input_file.Mean)**2 )/8
input_file['Standard_Deviation'] = input_file['Variance']**0.5
input_file['Skewness'] = ( (input_file.point1 - input_file.Mean)**3 + (input_file.point2 - input_file.Mean)**3 + (input_file.point3 - input_file.Mean)**3 + (input_file.point4 - input_file.Mean)**3 + (input_file.point5 - input_file.Mean)**3 + (input_file.point6 - input_file.Mean)**3 + (input_file.point7 - input_file.Mean)**3 + (input_file.point8 - input_file.Mean)**3 )/(8*((input_file.Standard_Deviation)**3))
input_file['Kurtosis'] = ( (input_file.point1 - input_file.Mean)**4 + (input_file.point2 - input_file.Mean)**4 + (input_file.point3 - input_file.Mean)**4 + (input_file.point4 - input_file.Mean)**4 + (input_file.point5 - input_file.Mean)**4 + (input_file.point6 - input_file.Mean)**4 + (input_file.point7 - input_file.Mean)**4 + (input_file.point8 - input_file.Mean)**4 )/(8*((input_file.Standard_Deviation)**4))
input_file['Crest_Factor'] = (input_file.Peak)/(input_file.Root_Mean_Square)
input_file['K_Factor'] = (input_file.Peak)*(input_file.Root_Mean_Square)
input_file

point1  point2  point3  point4  ...  Skewness  Kurtosis  Crest_Factor  K_Factor
0    0.200   0.200   0.200   0.202  ...  0.717206  1.794293      1.010562  0.040778
1    0.199   0.198   0.192   0.202  ... -0.559869  1.976440      1.021342  0.039951
2    0.200   0.198   0.193   0.183  ...  0.650633  1.658231      1.063041  0.037628
3    0.200   0.192   0.193   0.202  ...  0.435344  1.637692      1.062342  0.038409
4    0.197   0.197   0.200   0.192  ... -0.394714  1.325747      1.066155  0.037518
5    0.201   0.200   0.195   0.196  ...  0.042498  1.110438      1.079011  0.037443
6    0.200   0.198   0.192   0.162  ...  0.551438  1.381944      1.132334  0.035325
7    0.193   0.202   0.198   0.196  ... -1.046670  2.299093      1.061425  0.038443
8    0.202   0.193   0.194   0.199  ...  0.020805  1.099408      1.136645  0.035899
9    0.200   0.202   0.153   0.154  ...  1.135297  2.325583      1.201254  0.033968
10   0.201   0.202   0.200   0.196  ... -0.000369  1.017790      1.190299  0.034280
11   0.198   0.192   0.196   0.193  ... -0.508120  1.282598      1.138559  0.034433

[12 rows x 18 columns]

In [138]:
#Feature that will be inputed to our ML algorithm
input_features = input_file.drop(['point1','point2','point3','point4','point5','point6','point7','point8','Peak','Root_Mean_Square','Variance','Crest_Factor','K_Factor'],axis='columns') 
input_features
#input_for_ann = [[0.200875,0.040352,0.001166,0.717206,1.794293],[0.197750,0.039116,0.003382,-0.559869,1.976440],[0.188000,0.035397,0.007246,0.650633,1.658231],[0.190000,0.036156,0.007450,0.435344,1.637692],[0.187250,0.035190,0.011289,-0.394714,1.325747],[0.185875,0.034701,0.012303,0.042498,1.110438],[0.175875,0.031197,0.016275,0.551438,1.381944],[0.189750,0.036218,0.014592,-1.04667,2.299093],[0.176500,0.031583,0.020755,0.020805,1.099408],[0.167000,0.028277,0.019698,1.135297,2.325583],[0.166375,0.028800,0.033455,-0.000369,1.017790],[0.171375,0.030243,0.029551,-0.508120,1.282598]]

Mean  Mean_Square  Standard_Deviation  Skewness  Kurtosis
0   0.200875     0.040352            0.001166  0.717206  1.794293
1   0.197750     0.039116            0.003382 -0.559869  1.976440
2   0.188000     0.035397            0.007246  0.650633  1.658231
3   0.190000     0.036156            0.007450  0.435344  1.637692
4   0.187250     0.035190            0.011289 -0.394714  1.325747
5   0.185875     0.034701            0.012303  0.042498  1.110438
6   0.175875     0.031197            0.016275  0.551438  1.381944
7   0.189750     0.036218            0.014592 -1.046670  2.299093
8   0.176500     0.031583            0.020755  0.020805  1.099408
9   0.167000     0.028277            0.019698  1.135297  2.325583
10  0.166375     0.028800            0.033455 -0.000369  1.017790
11  0.171375     0.030243            0.029551 -0.508120  1.282598

In [139]:
#output that will associate with our input features 
output_file = main_file.Status
output_file

0     0
1     0
2     1
3     1
4     2
5     2
6     3
7     3
8     4
9     4
10    5
11    5
Name: Status, dtype: int64

In [140]:
#we will test which model will be best model that can give max accuracy
from sklearn.model_selection import GridSearchCV
#importing possible models that could help in making good decisions whether 
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression,LinearRegression 
from sklearn.naive_bayes import MultinomialNB 
from sklearn.tree import DecisionTreeClassifier 

In [141]:
#Testing with SVM
model = SVC(C=10,kernel='poly')
model.fit(input_features,output_file)
model.score(input_features,output_file)

0.8333333333333334

In [142]:
#predicted result from SVM
model.predict(input_features)

array([0, 0, 1, 1, 2, 2, 1, 3, 2, 4, 5, 5])

In [143]:
#Testing with Logistic Regression
model = LogisticRegression()
model.fit(input_features,output_file)
model.score(input_features,output_file)

0.3333333333333333

In [144]:
#predicted result from Logistic Regresssion
model.predict(input_features)

array([4, 3, 4, 4, 5, 5, 1, 3, 5, 4, 5, 5])

In [145]:
#Testing with Linear Regression
model = LinearRegression()
model.fit(input_features,output_file)
model.score(input_features,output_file)

0.9822405769560238

In [146]:
#predicted result from Linear Regression
model.predict(input_features)

array([-0.3341966 ,  0.09266362,  1.35554478,  1.3371897 ,  1.82912317,
        2.05250671,  2.95983249,  3.00157145,  3.61654209,  3.87406716,
        5.25176541,  4.96339002])

In [147]:
#Testing with Tree classifier
model = DecisionTreeClassifier()
model.fit(input_features,output_file)
model.score(input_features,output_file)

1.0

In [148]:
#predicted result from Tree Classifier
model.predict(input_features)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [149]:
#Testing with Random Forest
model = RandomForestClassifier()
model.fit(input_features,output_file)
model.score(input_features,output_file)

1.0

In [150]:
#predicted result from Random Forest
model.predict(input_features)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [151]:
#here onward we will work on ANN
#Scaling our data so that we could find a better prediction
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
input_features['Mean'] = scaler.fit_transform(input_features[['Mean']])
input_features['Mean_Square'] = scaler.fit_transform(input_features[['Mean_Square']])
input_features['Standard_Deviation'] = scaler.fit_transform(input_features[['Standard_Deviation']])
input_features['Skewness'] = scaler.fit_transform(input_features[['Skewness']])
input_features['Kurtosis'] = scaler.fit_transform(input_features[['Kurtosis']])
input_features

Mean  Mean_Square  Standard_Deviation  Skewness  Kurtosis
0   1.000000     1.000000            0.000000  0.808388  0.593751
1   0.909420     0.897672            0.068631  0.223102  0.733029
2   0.626812     0.589601            0.188292  0.777878  0.489712
3   0.684783     0.652457            0.194614  0.679210  0.474006
4   0.605072     0.572499            0.313509  0.298793  0.235479
5   0.565217     0.531992            0.344913  0.499168  0.070843
6   0.275362     0.241809            0.467917  0.732416  0.278449
7   0.677536     0.657633            0.415821  0.000000  0.979745
8   0.293478     0.273786            0.606664  0.489226  0.062409
9   0.018116     0.000000            0.573935  1.000000  1.000000
10  0.000000     0.043302            1.000000  0.479522  0.000000
11  0.144928     0.162783            0.879079  0.246818  0.202485

In [152]:
#making our data for ANN
input_for_ann = [[col['Mean'],col['Mean_Square'],col['Standard_Deviation'],col['Skewness'],col['Kurtosis']] for index, col in input_features.iterrows()]
length = len(input_for_ann)
output_for_ann = [[0 for a in range(6)] for b in range(length)]
for a in range(length):
  output_for_ann[a][output_file[a]] = 1
print(input_for_ann)
print(output_for_ann)

[[1.0, 1.0, 0.0, 0.8083881868130361, 0.5937505539289727], [0.9094202898550732, 0.8976718667508612, 0.068630565336004, 0.2231018823727084, 0.7330291424115443], [0.6268115942028984, 0.5896005217337295, 0.1882919518701548, 0.7778776119631771, 0.48971172558501963], [0.6847826086956523, 0.6524570139025472, 0.1946143402825748, 0.6792103315187549, 0.4740062186691396], [0.6050724637681162, 0.5724992494901704, 0.3135088607841205, 0.2987926666343892, 0.23547854304606664], [0.5652173913043477, 0.5319924224386914, 0.34491264226092755, 0.4991678010916467, 0.07084297391909677], [0.27536231884058004, 0.24180909100319825, 0.46791664628471236, 0.732416341612343, 0.27844911628559843], [0.6775362318840576, 0.6576329437583457, 0.41582086652789624, 0.0, 0.9797451290416224], [0.2934782608695654, 0.27378598565232215, 0.6066639455487958, 0.48922621465896204, 0.062409210207191146], [0.018115942028986254, 0.0, 0.5739345103608281, 1.0, 1.0], [0.0, 0.043301829173610695, 0.9999999999999999, 0.47952197245324074, 0.

In [153]:
#implementing our ANN
from tensorflow import keras 
model = keras.Sequential()
model.add(keras.Input(shape=(5,)))
#model.add(keras.layers.Dense(15, activation='relu'))
model.add(keras.layers.Dense(10, activation='relu'))
model.add(keras.layers.Dense(6,activation='sigmoid'))
model.compile(
    optimizer='adam',
    loss='mean_absolute_error',
    metrics = ['accuracy']
)
model.fit(input_for_ann,output_for_ann, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 0.4962 - accuracy: 0.2500
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 0.4955 - accuracy: 0.2500
Epoch 3/10
1/1 [==============================] - 0s 962us/step - loss: 0.4948 - accuracy: 0.2500
Epoch 4/10
1/1 [==============================] - 0s 877us/step - loss: 0.4941 - accuracy: 0.2500
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 0.4935 - accuracy: 0.2500
Epoch 6/10
1/1 [==============================] - 0s 992us/step - loss: 0.4928 - accuracy: 0.2500
Epoch 7/10
1/1 [==============================] - 0s 895us/step - loss: 0.4921 - accuracy: 0.2500
Epoch 8/10
1/1 [==============================] - 0s 929us/step - loss: 0.4914 - accuracy: 0.2500
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 0.4907 - accuracy: 0.2500
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.4901 - accuracy: 0.2500


In [154]:
#predicting from our ANN model
predict_value = model.predict(input_for_ann)
import numpy as np
real_predicted_values = [np.argmax(i) for i in predict_value]
real_predicted_values

[0, 0, 2, 0, 0, 3, 3, 1, 3, 1, 3, 1]